//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashCouponRecords
    {
        public System.Guid CashCouponID { get; set; }
        public string Mch_Billno { get; set; }
        public Nullable<int> CashAmount { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public string ResultCode { get; set; }
        public string ResultMessage { get; set; }
        public Nullable<int> CostScore { get; set; }
        public Nullable<System.Guid> SubscribeID { get; set; }
        public Nullable<System.Guid> AccountID { get; set; }
    
        public virtual OfficialAccounts OfficialAccounts { get; set; }
        public virtual Subscribes Subscribes { get; set; }
    }
}
