//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public System.Guid OrderID { get; set; }
        public Nullable<System.Guid> GoodID { get; set; }
        public Nullable<System.Guid> SubscribeID { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string ZipCode { get; set; }
        public string ContactPerson { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> AccountID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string ExpressCompany { get; set; }
        public string ExpressNumber { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual OfficialAccounts OfficialAccounts { get; set; }
        public virtual Subscribes Subscribes { get; set; }
        public virtual Users Users { get; set; }
    }
}
