//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscriber()
        {
            this.CashCouponRecord = new HashSet<CashCouponRecord>();
            this.Goods_Order = new HashSet<Goods_Order>();
        }
    
        public System.Guid SubscribeID { get; set; }
        public string NickName { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> SubscribeTime { get; set; }
        public string OpenID { get; set; }
        public string FromOpenID { get; set; }
        public Nullable<System.Guid> AccountID { get; set; }
        public Nullable<int> Sex { get; set; }
        public string HeadImgUrl { get; set; }
        public Nullable<bool> IsOK { get; set; }
        public Nullable<System.DateTime> UnSubscribeTime { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Precision { get; set; }
        public Nullable<System.DateTime> LocationTime { get; set; }
        public Nullable<int> SubscribeNumber { get; set; }
        public Nullable<int> SignScore { get; set; }
        public Nullable<int> DirectScore { get; set; }
        public Nullable<int> IndirectScore { get; set; }
        public Nullable<System.DateTime> SignLastTime { get; set; }
        public Nullable<int> SignContinuityCount { get; set; }
        public Nullable<System.DateTime> DirectScoreUpdateTime { get; set; }
        public Nullable<System.DateTime> IndirectScoreUpdateTime { get; set; }
        public Nullable<int> UnSubscribeCount { get; set; }
        public Nullable<int> ScoreUsed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashCouponRecord> CashCouponRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Goods_Order> Goods_Order { get; set; }
        public virtual OfficialAccount OfficialAccount { get; set; }
    }
}
