//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateMessage
    {
        public System.Guid TemplateID { get; set; }
        public string TemplateCode { get; set; }
        public Nullable<System.Guid> CategoryID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> AccountID { get; set; }
    
        public virtual OfficialAccount OfficialAccount { get; set; }
        public virtual Template_Category Template_Category { get; set; }
    }
}
