//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WSDBEntities : DbContext
    {
        public WSDBEntities()
            : base("name=WSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account_QRCode_Template> Account_QRCode_Template { get; set; }
        public virtual DbSet<AutoReply> AutoReply { get; set; }
        public virtual DbSet<AutoReply_Category> AutoReply_Category { get; set; }
        public virtual DbSet<CashCouponRecord> CashCouponRecord { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<Goods_Category> Goods_Category { get; set; }
        public virtual DbSet<Goods_Order> Goods_Order { get; set; }
        public virtual DbSet<Goods_SendWay> Goods_SendWay { get; set; }
        public virtual DbSet<OfficialAccount> OfficialAccount { get; set; }
        public virtual DbSet<QRCode_Template> QRCode_Template { get; set; }
        public virtual DbSet<Subscriber> Subscriber { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Template_Category> Template_Category { get; set; }
        public virtual DbSet<TemplateMessage> TemplateMessage { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Users_Role> Users_Role { get; set; }
    }
}
